### ISSUE TITLE
Add reference to talk about "Sociotechnical Architecture" of Eduardo da Silva

### ISSUE THREAD

**Issue by cremich** [ddd-crew/ddd-starter-modelling-process#14]
Hey everyone, 

I watched the talk mentioned in the issue title.
My first thought after this was: very helpful in terms of understanding the steps of the starter modelling process. 

How do you think about adding some kind of reference to this talk in the readme:

https://www.youtube.com/watch?v=ekMPm78KFj0

The introduction into the modellling process starts here:
https://youtu.be/ekMPm78KFj0?t=1820

Best,
Christian

**Comment by NTCoding** [comment]
Yeah definitely. WE should add a link to that talk.

**Comment by yellowbrickc** [comment]
Hi @cremich I will happily click on the merge button, just send an MR :) I didn't see the talk yet so you can better estimate where would be the best place for the reference.
