### ISSUE TITLE
Add reference to the other repos in ddd-crew

### ISSUE THREAD

**Issue by yellowbrickc** [ddd-crew/ddd-starter-modelling-process#15]
Hi everyone,
This repo is the starting point for all the other "detailed descriptions" in the other repos but we don't reference them yet.
What do you think, should we add a link to every chapter referencing the corresponding repo (if exists)?

**Comment by NTCoding** [comment]
Hey @yellowbrickc.

I would recommend keeping separate an index of all repositories and the starter process itself for a few reasons:

1. There may be other processes that also use the other techniques

2. There may be other techniques we add that aren't referenced in this process

For an index of all the repos, I think creating a separate repository would be better.

What do you think?

**Comment by yellowbrickc** [comment]
I'm not sure, we are talking about the same thing.
I was explaining my CTO (who is in the middle of product strategy discussions and needs to document and visualize a lot of things) that he could take some time to not waste time later :) I proposed him to start here and take a look at the more template for the Wardley map - and I wasn't able to find it :( The @ddd-crew/crew had collected so many good things that I cannot remember anymore where is which template/explanation.

I mean some reference like we already do with tools. Example: we reference the Business Model Canvas - but not the Repo but the original site. My question is: wouldn't be good to add a link to the corresponding repo as a reference or with a comment?

**Comment by NTCoding** [comment]
Hi @yellowbrickc. Could you provide a very small example of this?

**Comment by yellowbrickc** [comment]
I just did 😄 
What I still didn't find is the template for Wardley map and I'm sure that we have it somewhere... I really would like to add it to the starting repo.

**Comment by NTCoding** [comment]
For Wardley Mapping I've been using the Miro template and higly recommend it: https://miro.com/blog/wardley-maps-whiteboard-canvas/. I don't recall us creating a Wardley Mapping template in DDD Crew.
