### ISSUE TITLE
Source file of the images

### ISSUE THREAD

**Issue by raulexposito** [ddd-crew/ddd-starter-modelling-process#31]
Hi,

I will be very grateful if you could share the source of the images to translate them to Spanish. I asked you something similar in https://github.com/ddd-crew/welcome-to-ddd/issues/3

Thanks in advance and regards

**Comment by yellowbrickc** [comment]
@NTCoding do you have something including all these resources too? Maybe do you (as the ultimate power-user of miro 😉 ) have a miro-project where these templates can live? Or do you have another idea where to keep them so that they can be easily shared and maybe evolved?

**Comment by NTCoding** [comment]
I believe this should work, and it has copy and paste enabled: https://miro.com/app/board/o9J_laNkYxM=/?share_link_id=429755130022

**Comment by raulexposito** [comment]
Thanks for your help, but perhaps I didn't explain myself correctly. Sorry, my fault.

The images I'm asking the sources of are the following ones:
https://github.com/ddd-crew/ddd-starter-modelling-process/tree/master/resources

Would you mind sharing them?

Regards

**Comment by NTCoding** [comment]
Oh my apologies. Those resources are coming from different sources.

Aggregate design canvas - @cakper 

Bounded Context Canvas, Core Domain Chart, Message Flow - https://miro.com/app/board/uXjVO2rOaEw=/?share_link_id=198096946849

Context Mapping & Start Modeling Process - @mploed

**Comment by emgsilva** [comment]
@raulexposito this is a great initiative, I just have a word of caution: these are rather "dynamic" resources (a lot of them change regularly), and as Nick shared they are maintained rather "organically" by different people (using different tools, etc.). So I wonder if translations will not quickly go out of sync. Maybe it still pays off on doing them (please assess that), or some sort of mid-way (translate "introduction" of the techniques - i.e.: the repos README, and leave actual "templates" - images - in English).

**Comment by Max-Git** [comment]
Back in 2020 I translated some resources in French for the Bounded Context Canvas repository. It was for the purpose of a blog post, I did not make any announcement for those. I did just put them in the [resources](https://github.com/ddd-crew/bounded-context-canvas/tree/master/resources) folder. 
Now I'm wondering if translations are growing maybe we should have a dedicated folder per language and write it in the README that people can have a look if resources are available in their language.

**Comment by Max-Git** [comment]
@yellowbrickc  I've created a `translations` folder in the Starter Modelling Process repo and in the BC Canvas repo. I moved all the French content in there.  ([6116807](https://github.com/ddd-crew/ddd-starter-modelling-process/commit/6116807270fadea797ab4f9b151c5d45ee5aaba5) and [8305134](https://github.com/ddd-crew/bounded-context-canvas/commit/830513433fdf9cddfecbde1545653c6a10aded07))

**Comment by yellowbrickc** [comment]
You are the best @Max-Git !!

**Comment by jlasoc1** [comment]
I'm going to add the images that I have in spanish
