### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by fdamico** [ddd-crew/ddd-starter-modelling-process#39]
Hi there, if it can be helpful I can translate the image into my native language (Italian) at this location --> ddd-starter-modelling-process/tree/master/translations

If so, just let me know where I can find the original drawing or which tool you guys used.

Cheers

**Comment by fdamico** [comment]
ok, I've done the translation and saved it in a local branch. If u give me write access I can push the branch and then I can open a PR or instruct me on how would you like to proceed. Cheers

**Comment by Max-Git** [comment]
You should be able to push your branch. Thanks!
