### ISSUE TITLE
Inside-out DDD process

### ISSUE THREAD

**Issue by Baasie** [ddd-crew/ddd-starter-modelling-process#4]
The current DDD starter process describes going from the outside-in. From strategic to tactical. A lot of people are not in the position to do so or don't have the resources/capabilities to do so.

I want to start to describe that process of how you would do that from the inside-out perspective.
 What do you think?

**Comment by NTCoding** [comment]
Hey @Baasie. 

Thanks for suggesting this. I think an inside-out modelling process could also be useful. 

I do have some slight hesitations about jumping into tactical DDD without understanding the business and modelling the domain, but I think if you can explain in a tiny bit more detail I'm sure I would agree 100%.

Thanks

**Comment by Baasie** [comment]
Yeah what I mean is not start at the bigger picture, but form the as-is process from your team perspective. Find gaps in knowledge of that flow, find the stakeholder and find potential boundries. Move to to-be process modelling or bounded context canvas to find a bounded context from your team perspective.

**Comment by NTCoding** [comment]
What do you propose for the next steps? Anything I can help with?

**Comment by Baasie** [comment]
We can do a zoom collaborative eventstorming the process if you want :D

**Comment by NTCoding** [comment]
I'm in!

**Comment by Baasie** [comment]
I will tomorrow start planning a Virtual-DDD meetup

**Comment by NTCoding** [comment]
I think we will probably touch on this topic in the next meetup where we discuss DDD for newcomers https://www.meetup.com/dddlondon/events/270693800/ so it would be a good follow-on to zoom in on inside-out.

**Comment by yellowbrickc** [comment]
Hi @Baasie, @NTCoding 
we had a few meetups regarding this already. I would propose to write down everything we know for now before all that valuable insights are lost. 
If you agree, here my next question: Kenny would you start with what you have, or would you like to start with some kind of mob writing?

**Comment by NTCoding** [comment]
@yellowbrickc good question. Should we start by listing in here all of the content we have created so far?

I believed that the outcome of the previous meetup was that we would have a follow-up meetup to start co-creating the individual sections of the documentation.

**Comment by Baasie** [comment]
Yes, let me start with it next week @yellowbrickc

**Comment by yellowbrickc** [comment]
This issue hasn't aged well 😆 I would say it is not needed anymore; I close it. Feel free to reopen it if you want to work on it ("you" = anyone here with a good idea and enough time and energy).
