### ISSUE TITLE
Reference to DDD Kata at SAP

### ISSUE THREAD

**Issue by neolytian** [ddd-crew/ddd-starter-modelling-process#41]
Hi DDD Crew!

Where would be the best place to put the reference to the DDD Kata used at SAP? 
https://github.com/SAP/curated-resources-for-domain-driven-design/blob/main/ddd-kata.md 

Thank you!

Best Regards, Philipp

**Comment by yellowbrickc** [comment]
What about a new line in the section https://github.com/ddd-crew/ddd-starter-modelling-process/blob/master/README.md#practicing-or-learning-ddd ?

**Comment by yellowbrickc** [comment]
Happy New Year @neolytian 🎉 

Would you create a PR to add this new section to connect the dots or would you rather keep the 2 repos separated?

**Comment by neolytian** [comment]
Hi! 

I wish you happy new year yourself. I have opened a PR https://github.com/ddd-crew/ddd-starter-modelling-process/pull/44 

Best Regards, @neolytian

**Comment by yellowbrickc** [comment]
Thanks, @neolytian!
