### ISSUE TITLE
Suggestions for adding the user perspective

### ISSUE THREAD

**Issue by trondhjort** [ddd-crew/ddd-starter-modelling-process#9]
Hi,

Sendt this as a comment to #1, but after it was merged. Try here instead. 

Great stuff this, even though I'm a bit worried that people with copy it whole-cloth and end up over-designing. Let's hope not.

I have a couple of comments:

- Step 1: You mention user need in the process illustration, but can't see it mentioned in the description. I think User Story Mapping would fit perfectly there, done in collaboration with biz and UX. Add a couple of sentences on it and link to https://www.jpattonassociates.com/user-story-mapping/

- Step 2: I think the user perspective is also often missed here, and find that user story mapping is also beneficial here to make all agree on what we would like to support when (slices in the story map).

- Step 4: Simon Brown has some extension to his C4 model which I have used and like, Dynamic Diagram (https://c4model.com/#SupplementaryDiagrams)

If you haven't seen it, also like Andrew Hamel-Law's post on starting with DDD: https://www.thoughtworks.com/insights/blog/domain-driven-design-neednt-be-hard-heres-how-start

That's it. Thank you for including Business Capability Modelling.

**Comment by cakper** [comment]
Hi @trondhjort! Thank you for your comment and sorry for missing in on the previous PR.

I'm using User Story Mapping myself and find it helpful as well. Do you think it makes more sense to do it at step 1 or 2? I'd be leaning towards two, but I'm open to discussion.

Re Simon's diagrams - sure, let's add it! 

Regarding Andrew's article - I think this is going to be a perfect resource to add to the playbook people are creating during the meetup tonight.

**Comment by trondhjort** [comment]
As mentioned I think it belongs to both, must mostly in the first. Having the biz AND the user perspective is at least in my experience essential. In story mapping often do the initial product discovery as the triad, with UX, Biz and IT. I wrote about this on the Visual Collaboration Tools book.

**Comment by NTCoding** [comment]
@cakper @trondhjort How about we create another repo which contains a link to blog posts and other free resources for learning DDD? Andrew Harmel-Law's post for example.

**Comment by trondhjort** [comment]
Good suggestion, but still think user story mapping (or similar) belongs in the starting guide as that is all too frequently ignored as I see it. A lot of focus on the business, less on the customers and its users.

**Comment by NTCoding** [comment]
@trondhjort sorry Trond, wasn't arguing against user story mapping. I was thinking of where we could put resources like Andrew's article. It doesn't seem like we should keep adding links to resources in this repo but it is necessary to put them somewhere.

Regarding user story mapping, it kind of fits in both 1 and 2 doesn't it. it's about mapping out the user's needs, and it's also about mapping those needs onto the user's journey throughout the domain.

**Comment by trondhjort** [comment]
Yes, as mentioned above, it does belong in both, although different aspects of it. It has layers, like event storming. First it is used for discovering/exploring the product and matching it to the business needs in a feasible manner (hence the triad; UX, Biz, IT). Later it can be used to plan your delivery, in increments, structuring the product backlog. The latter is where most teams use it in agile shops, often replacing Jira. 😉

**Comment by NTCoding** [comment]
@trondhjort I'll go make a coffee while you put that PR together 😉

**Comment by trondhjort** [comment]
See PR.
